theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  debug: true
  search:
    active: true
  organizations:
    single:
      backlinks: true
  persons:
    single:
      backlinks: true