theme: osuny-hugo-theme-aaa

## ADVANCED
paginate: 2
enableRobotsTXT: true

## MODULE
module:
  _merge: deep

## PARAMS
params:
  _merge: deep
  cookie_banner:
    enable: false
  posts:
    list:
      show_categories: true

build:
  writeStats: true

removePathAccents: true
