posts:          /accueil/actualites/:year/:month/:day/:slug/
categories:     /accueil/actualites/:slug/
persons:        /accueil/equipe/:slug/
authors:        /accueil/equipe/:slug/actualites/
teachers:       /accueil/equipe/:slug/programs/
researchers:    /accueil/equipe/:slug/articles/
